name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    if: "!contains(github.event.head_commit.message, '[SKIP BACKEND BUILD]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'
        cache-dependency-path: 'backend'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend'

    - name: Build
      run: 'make -j2'
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7.0.0
      with:
        name: Backend and Frontend
        path: "build"
          
